### ISSUE TITLE
No longer building correctly

### ISSUE THREAD

**Issue by kopiezzo** [SimpsomRJ/docker-bazarr-mod-subsync#1]
Hey, this image started to not build correctly, subsync is not working anymore, im attaching the log, is it fixable?
[_bazarr_logs (2).txt](https://github.com/SimpsomRJ/docker-bazarr-mod-subsync/files/10950789/_bazarr_logs.2.txt)

**Comment by SimpsomRJ** [comment]
The subsonic software isn't being maintained anymore. That's why this is failing. I could not find a solution for that.
